name: docker
author: outblocks
usage: Docker run plugin
description: Run whole stack locally through docker containers
cmd:
  default: $OUTBLOCKS_PLUGIN_DIR/docker_plugin
  windows: $OUTBLOCKS_PLUGIN_DIR/docker_plugin.exe
actions:
  - run
commands:
  run:
    flags:
      - name: docker-regenerate
        type: boolean
        usage: Regenerate dockerfiles
      - name: docker-rebuild
        type: boolean
        usage: Rebuild docker images
      - name: docker-no-cache
        type: boolean
        usage: Skip cache when rebuilding docker images
      - name: docker-production
        type: boolean
        usage: Use production images rather than dev ones

supports:
  - service
  - static
supported_types:
  - type: postgresql
  - type: mysql
  - type: storage
    match:
      deploy: gcp
