name: docker
author: outblocks
usage: Docker run plugin
description: Run whole stack locally through docker containers
cmd:
  default: $OUTBLOCKS_PLUGIN_DIR/docker_plugin
  windows: $OUTBLOCKS_PLUGIN_DIR/docker_plugin.exe
actions:
  - run
commands:
  run:
    args:
      - name: docker-regenerate
        type: bool
        usage: Regenerate dockerfiles.
      - name: docker-rebuild
        type: bool
        usage: Rebuild docker images.
      - name: docker-no-cache
        type: bool
        usage: Skip cache when rebuilding docker images.

supports:
  - function
  - service
  - static
supported_types:
  - type: postgresql
  - type: mysql
  - type: storage
    match:
      deploy: gcp
