name: docker
author: outblocks
usage: Docker run plugin
description: Run whole stack locally through docker containers
cmd:
  default: $OUTBLOCKS_PLUGIN_DIR/docker_plugin
  windows: $OUTBLOCKS_PLUGIN_DIR/docker_plugin.exe
actions:
  - run
supports:
  - function
  - service
  - static
supported_types:
  - type: postgresql
  - type: storage
    match:
      deploy: gcp
