name: docker
author: outblocks
usage: Docker run plugin
description: Run whole stack locally through docker containers
run: $OUTBLOCKS_PLUGIN_DIR/docker_plugin
actions:
  - run
state_types:
  - gcp
supports:
  - function
  - service
  - static
supported_types:
  - type: postgresql
  - type: storage
    match:
      deploy: gcp
