# Automatically generated by Outblocks Docker plugin.
# DO NOT EDIT. Will be overwritten on next run.

version: "3.9"

services:
  {{.Name}}:
    build:
      context: .
      dockerfile: {{.Dockerfile}}
{{- if .DockerCommand }}
    command: {{.DockerCommand | toJson}}
{{ end }}
{{- if .DockerEntrypoint }}
    entrypoint: {{.DockerEntrypoint | toJson}}
{{ end }}
{{- if .WorkDir }}
    working_dir: {{.WorkDir}}
{{ end }}
    ports:
      - {{.Port}}:{{.ContainerPort}}

    environment:
{{.Env | toYaml | indent 6}}
    volumes:
      - .:{{.DockerPath | default "/devapp"}}
{{- range $key, $value := .Volumes }}
      - {{ $key }}:{{ $value }}
{{- end }}

    extra_hosts:
{{- range $key, $value := .Hosts }}
      - {{ $key }}:host-gateway
{{- end }}

{{- if .Volumes }}

volumes:
{{- range $key, $value := .Volumes }}
  {{ $key }}:
{{- end }}
{{- end }}
